# ./docker-compose.yml (최종본)

version: '3.8'

services:
  backend-blue:
    image: mschoi6641/crawling-service:${DOCKER_IMAGE_TAG_BLUE}
    container_name: backend-blue
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mariadb://yaguhangdb:3306/tourismcontest?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    networks:
      - yaguhang-net
    restart: always

  # 2. Green 버전의 스프링부트 애플리케이션
  backend-green:
    image: mschoi6641/crawling-service:${DOCKER_IMAGE_TAG_GREEN}
    container_name: backend-green
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mariadb://yaguhangdb:3306/tourismcontest?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    networks:
      - yaguhang-net
    restart: always

  # 3. 트래픽을 분배할 Nginx 프록시 서비스
  proxy:
    image: nginx:1.25-alpine
    container_name: proxy
    ports:
      # 외부의 80번 포트 요청을 Nginx의 80번 포트로 연결합니다.
      # 실제 서비스 포트(18080)는 외부에 노출하지 않습니다.
      - "80:80"
    volumes:
      # 다음 단계에서 생성할 Nginx 설정파일을 컨테이너에 연결합니다.
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/service-url.inc:/etc/nginx/conf.d/service-url.inc
    networks:
      - yaguhang-net
    depends_on:
      - backend-blue
      - backend-green
    restart: always

# 이 docker-compose가 사용할 네트워크를 정의합니다.
networks:
  yaguhang-net:
    # 'yaguhang-bridge'라는 이름의 이미 존재하는 외부 네트워크를 사용합니다.
    name: yaguhang-bridge
    external: true