version: '3.8'

services:
  crawling-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: mschoi6641/crawling-service:latest
    container_name: crawler-build
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mariadb://yaguhangdb:3306/tourismcontest?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    expose:
      - "18080"
    networks:
      - yaguhang-bridge

networks:
  yaguhang-bridge:
    external: true