name: CI/CD for Crawling Service

on:
  push:
    branches: [ main ]

jobs:
  # 1. 빌드 및 이미지 푸시 작업
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 태그를 2개(latest, 커밋해시)로 지정하여 푸시
          tags: |
            mschoi6641/crawling-service:latest
            mschoi6641/crawling-service:${{ github.sha }}
          network: yaguhang-bridge

  # 2. 배포 작업
  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Grant execute permission to deploy script
        run: chmod +x ./scripts/deploy.sh

      # 배포 스크립트 실행
      - name: Run deploy script
        run: bash ./scripts/deploy.sh ${{ github.sha }}