name: CI/CD for Crawling Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy external config files
        run: |
          echo "Ensuring destination directory exists..."
          mkdir -p ./src/main/resources
          echo "Copying configuration files..."
          cp /home/mschoi/Desktop/tourismContest/Yaguhang-RE/crawling-service/env/* ./src/main/resources/

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            mschoi6641/crawling-service:latest
            mschoi6641/crawling-service:${{ github.sha }}
          network: host
          cache-from: type=registry,ref=mschoi6641/crawling-service:latest
          cache-to: type=inline

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Convert CRLF to LF for deploy script
        run: dos2unix ./scripts/deploy.sh

      - name: Grant execute permission to deploy script
        run: chmod +x ./scripts/deploy.sh

      - name: Run deploy script
        run: bash ./scripts/deploy.sh ${{ github.sha }}